bowcal/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tournaments/', include('tournaments.urls')),
)

tournaments/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
    url(r'^$', views.TournamentList.as_view(), name='tournament-list'),
    url(r'^submit/$', views.TournamentSubmit.as_view(), name='tournament-submit'),
)

tournaments/models.py
from django.db import models


ARCHERY_TYPES = (
    ('I', 'Indoor Target'),
    ('O', 'Outdoor Target'),
    ('F', 'Field'),
    ('C', 'Clout'),
    ('W', 'Wand'),
    ('L', 'Flight'),
    ('H', 'Other'),
    ('M', 'Mixed'),
)


class Region(models.Model):
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=63)

    def __str__(self):
        return self.short_name


class County(models.Model):
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=63)
    region = models.ForeignKey(Region, blank=True, null=True)

    def __str__(self):
        return self.short_name

    class Meta:
        verbose_name_plural = 'counties'


class Club(models.Model):
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=63)
    county = models.ForeignKey(County, blank=True, null=True)

    def __str__(self):
        return self.short_name


class Round(models.Model):
    name = models.CharField(max_length=255)
    shoot_type = models.CharField(max_length=1, choices=ARCHERY_TYPES)

    def __str__(self):
        return self.name


class Series(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'series'


class Venue(models.Model):
    name = models.CharField(max_length=255)
    address_1 = models.CharField(max_length=255)
    address_2 = models.CharField(max_length=255, blank=True, default='')
    town = models.CharField(max_length=255, blank=True, default='')
    postcode = models.CharField(max_length=255, blank=True, default='')

    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.name


class Tournament(models.Model):
    RECORD_STATUSES = (
        ('None', 'No record status'),
        ('UKRS', 'UK record status'),
        ('WRS', 'World record status'),
        ('Rose', 'Rose & UK record status'),
        ('AH', 'Arrowhead'),
        ('Tassel', 'Tassel status'),
        ('TUKRS', 'Tassel & UK record status'),
    )

    STATUS_CHOICES = (
        ('listed', 'Listed'),
        ('open', 'Entries open'),
        ('full', 'Full'),
        ('ongoing', 'Happening now'),
        ('past', 'Completed'),
    )

    name = models.CharField(max_length=511)
    start_date = models.DateField()
    end_date = models.DateField()

    organising_club = models.ForeignKey(Club, blank=True, null=True)
    organising_county = models.ForeignKey(County, blank=True, null=True)
    series = models.ForeignKey(Series, blank=True, null=True)
    venue = models.ForeignKey(Venue, blank=True, null=True)

    status = models.CharField(max_length=31, choices=STATUS_CHOICES)
    shoot_type = models.CharField(max_length=1, choices=ARCHERY_TYPES)
    record_status = models.CharField(max_length=7, choices=RECORD_STATUSES)
    rounds = models.ManyToManyField(Round, blank=True)

    approved = models.BooleanField(default=False)
    submission_notes = models.TextField(blank=True, default='')

    def __str__(self):
        return self.name

    @property
    def organiser(self):
        return self.organising_club or self.organising_county

    @property
    def has_record_status(self):
        return not self.record_status == 'None'

tournaments/forms.py
from django import forms

from .models import Tournament


class TournamentSubmissionForm(forms.ModelForm):
    multi_day_shoot = forms.BooleanField(required=False)

    class Meta:
        model = Tournament
        fields = (
            'name',
            'start_date',
            'end_date',
            'organising_club',
            'organising_county',
            'series',
            'venue',
            'shoot_type',
            'record_status',
            'rounds',
            'submission_notes',
        )

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['end_date'].required = False

    def clean(self):
        if self.cleaned_data.get('multi_day_shoot') and not self.cleaned_data.get('end_date'):
            self.add_error('end_date', self.fields['end_date'].error_messages['required'])

    def save(self, **kwargs):
        if not self.cleaned_data['multi_day_shoot']:
            self.instance.end_date = self.instance.start_date
        return super().save(**kwargs)

tournaments/views.py
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone
from django.views.generic import TemplateView, CreateView

from braces.views import MessageMixin

from .forms import TournamentSubmissionForm
from .models import Tournament


class TournamentList(TemplateView):
    template_name = 'tournaments/tournament_list.html'

    def get_tournaments(self):
        return Tournament.objects.filter(
            end_date__gte=timezone.now().date,
            approved=True,
        ).select_related(
            'organising_club',
            'organising_county',
            'venue',
        ).prefetch_related('rounds').order_by(
            'start_date',
            'end_date',
        )

    def get_context_data(self, **kwargs):
        return {
            'tournaments': self.get_tournaments(),
        }


class TournamentSubmit(MessageMixin, CreateView):
    template_name = 'tournaments/tournament_submit.html'
    form_class = TournamentSubmissionForm
    success_url = reverse_lazy('tournament-list')

    def form_valid(self, form):
        self.messages.info('Your submission has been received.')
        return super().form_valid(form)

templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>BowCal</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container-fluid">
            {% for message in messages %}
            <div class="alert alert-{{ message.level }}">{{ message }}</div>
            {% endfor %}
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

tournaments/templates/tournaments/tournament_list.html
{% extends 'base.html' %}


{% block content %}
<h1>Tournament list</h1>
<a class="btn btn-default" href="{% url 'tournament-submit' %}">Submit a tournament</a>
<table class="table">
    <thead>
        <tr>
            <th>Discipline</th>
            <th>Tournament</th>
            <th>Date(s)</th>
            <th>Organiser</th>
            <th>Round(s)</th>
            <th>Venue</th>
            <th>Status</th>
        </tr>
    </thead>
    {% for tournament in tournaments %}
    <tr>
        <td>{{ tournament.get_shoot_type_display }}</td>
        <td>{{ tournament.name }}</td>
        <td>{{ tournament.start_date }}{% if not tournament.start_date == tournament.end_date %} to {{ tournament.end_date }}{% endif %}</td>
        <td>{{ tournament.organiser }}</td>
        <td>
            {% if tournament.has_record_status %}
            <span class="status">{{ tournament.get_record_status_display }}</span>
            {% endif %}
            <ul>
                {% for round in tournament.rounds.all %}
                <li>{{ round }}</li>
                {% endfor %}
            </ul>
        </td>
        <td>{% if tournament.venue %}{{ tournament.venue }}{% endif %}</td>
        <td>{{ tournament.get_status_display }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

tournaments/templates/tournaments/tournament_submit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content %}
<h1>Submit tournament</h1>
<form method="POST" action="{{ request.get_full_path }}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="ctrl-holder">
        <input type="submit" class="btn btn-success">
    </div>
</form>
{% endblock %}